# Generated by Django 4.2.11 on 2024-03-31 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontentreadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_read_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='course_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_content', to='course.coursemodule'),
        ),
    ]
