# Generated by Django 4.2.8 on 2024-03-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualtour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
