# Generated by Django 4.2.8 on 2024-03-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualtour', '0002_alter_tour_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='tour',
            name='scenes',
            field=models.IntegerField(default=0, verbose_name='Scenes'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tour Title'),
        ),
    ]
