# Generated by Django 4.2.8 on 2024-03-31 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualtour', '0004_tour_latitude_tour_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Video')),
                ('ordering', models.IntegerField(default=1, verbose_name='Ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='virtualtour.tour')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
    ]
