# Generated by Django 4.2.11 on 2024-03-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classic',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('create_time', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('author', models.CharField(default='1827316887@qq.com', max_length=255)),
                ('likes', models.BigIntegerField(default=0)),
                ('img', models.ImageField(default='avatar-2024033113040001029.jpg', upload_to='images')),
            ],
            options={
                'db_table': 'classic',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('comment_time', models.CharField(max_length=255)),
                ('pre_id', models.BigIntegerField()),
                ('author_email', models.CharField(max_length=255)),
                ('classicid', models.BigIntegerField()),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
